# Generated by Django 2.1.4 on 2018-12-09 10:41

from django.db import migrations, models
import memories.models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='media',
            field=models.FileField(blank=True, default='', upload_to=memories.models.user_directory_path),
        ),
    ]
