# Generated by Django 2.1.4 on 2018-12-09 11:36

from django.db import migrations, models
import memories.models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0003_auto_20181209_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to=memories.models.user_directory_path),
        ),
    ]
