# Generated by Django 2.1.4 on 2018-12-09 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0004_auto_20181209_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='mime_type',
            field=models.CharField(default='', max_length=30),
        ),
    ]
